import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Poppins } from "next/font/google";
import Clock from "@/components/Clock";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Clock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${poppins.className}`}>
        <Clock locale="en-CA" />
      </main>
    </>
  );
}
